# Refreshing Python

In [1]:
a=5
b=2.0
a+b

7.0

Variables are persistent

In [2]:
a

5

Old style of formating in print statement

In [3]:
print("a=%d b=%s" % (a, b))

a=5 b=2.0


New and recommended style (see more [here](https://www.python-course.eu/python3_formatted_output.php))

In [4]:
print("a={} b={}".format(a,b))

a=5 b=2.0


Operator // is integer division; The power operator is **

In [5]:
3.0 // 2.0

1.0

In [6]:
2 ** 3

8

### Functions

In [7]:
def suma(a,b):
    return a+b

suma(2,a)

7

In [8]:
def suma2o3(a,b,c=None):
    """Add two or 3 numbers"""
    if(c==None):
        return a+b
    else:
        return a+b+c

help(suma2o3)
print(suma2o3(2,4))
print(suma2o3(2,4,6))

Help on function suma2o3 in module __main__:

suma2o3(a, b, c=None)
    Add two or 3 numbers

6
12


In [9]:
def suma2o3(a,b,c=None,flag=False):
    if(flag):
        print('Flag is True')
    if (c==None):
        return a+b
    else:
        return a+b+c
    
suma2o3(2,3,flag=True)

Flag is True


5

In [10]:
fun=suma
fun(3,5)

8

A function can return several values

In [11]:
def cube(a):
    return a,a**3
cube(2)

(2, 8)

In [12]:
x,y=cube(3)
print("The cube of {} is {}".format(x,y))

The cube of 3 is 27


### Types

In [13]:
type('This is a string')

str

In [14]:
type(None)

NoneType

In [15]:
type(1)

int

In [16]:
type(1.0)

float

In [17]:
type(suma)

function

### Tuples
Inmutable data type. Use parenthesis

In [18]:
x=(1,'a',3.8,'b')
type(x)

tuple

In [19]:
x[0]

1

In [20]:
x[1]

'a'

In [21]:
for i in x:
    print(i)
    

1
a
3.8
b


A tuple is unpacked like this:

In [22]:
x,y,z,p=x
print(x,y,z,p)

1 a 3.8 b


### Lists
Mutable data type. Use brackets.

In [23]:
x=[1,'a',3.8,'b']
type(x)

list

In [24]:
x

[1, 'a', 3.8, 'b']

In [25]:
x.append(4)
x

[1, 'a', 3.8, 'b', 4]

Concatenate lists with +

In [26]:
x=[1, 'a', 3.8, 'b', 4] + [2, 3.1]
x

[1, 'a', 3.8, 'b', 4, 2, 3.1]

Use * to repeat lists

In [27]:
y=[1,2]*3
y

[1, 2, 1, 2, 1, 2]

In [28]:
x.reverse()
x

[3.1, 2, 4, 'b', 3.8, 'a', 1]

Slicing:

In [29]:
x[1:2]

[2]

In [30]:
x[3:]

['b', 3.8, 'a', 1]

In [31]:
x[:3]

[3.1, 2, 4]

In [32]:
x[-3::-2]

[3.8, 4, 3.1]

### Creating lists

In [33]:
for i in range(-3,4,2):
    print(i)

-3
-1
1
3


In [34]:
for idx, x in enumerate(range(-3,3)):
             print(idx, x)

0 -3
1 -2
2 -1
3 0
4 1
5 2


### Dictionaries
Use curly braces

In [35]:
x={'2425':'Rafa','3333':'Pepe','1231':'Juan'}
x

{'2425': 'Rafa', '3333': 'Pepe', '1231': 'Juan'}

Dictionaries are indexed using the "key"

In [36]:
x['2425']

'Rafa'

In [37]:
x={2425:'Rafa',3333:'Pepe',1231:'Juan'}
x

{2425: 'Rafa', 3333: 'Pepe', 1231: 'Juan'}

In [38]:
x[2425]

'Rafa'

They can be iterated

In [39]:
for id in x:
    print(x[id])

Rafa
Pepe
Juan


In [40]:
for name in x.values():
    print(name)

Rafa
Pepe
Juan


In [41]:
for id,name in x.items():
    print("{1} tiene id {0}".format(id,name))

Rafa tiene id 2425
Pepe tiene id 3333
Juan tiene id 1231


###  Strings
A list of chars

In [42]:
firstname='Rafa'
lastname='Asenjo'
name=firstname+ ' '+ lastname
name

'Rafa Asenjo'

In [43]:
print(firstname*3)

RafaRafaRafa


In [44]:
print('Ra' in name)

True


In [45]:
name='Oscar Luis Alonso Lozano'
primero=name.split()[0]
ultimo=name.split()[-1]
print(primero+ ' '+ultimo)

Oscar Lozano


Convert to string befor concatenation

In [46]:
print(name+str(2))

Oscar Luis Alonso Lozano2


### List comprehension

In [47]:
l1 = [x**2 for x in range(0,5)]
print(l1)

[0, 1, 4, 9, 16]


Exercise: create a list with of the even numbers traversing the list range(0,1000). Use first a regular for and later come up with a better implementation using list comprehension.

In [48]:
#Using %2 inside a for loop

In [49]:
#Using %2 inside a list comprehension

In [50]:
#Using another argument of range

### Lambda function
Unnamed (anonymous) functions usefull to pass as argument to other functions

In [51]:
f1 = lambda x: x**2
# is equivalent to
def f2(x):
    return x**2

In [52]:
f1(2),f2(2)

(4, 4)

Example using the map python function. The map function has this signature
+ map(function_to_apply, list_of_inputs)

Say we want to compute the minimum of two lists. This is a posibility:

In [53]:
x=[1,3,5,8,2]
y=[-11,20,1,8,0]
z=[]
for i,j in zip(x,y):
    z.append(min(i,j))
    
print(z)

[-11, 3, 1, 8, 0]


But a more pythonic implementation looks like:

In [54]:
list(map(lambda x,y:min(x,y),x,y))

[-11, 3, 1, 8, 0]

Take care with the lazy evaluation:

In [55]:
z=map(lambda x,y:min(x,y),x,y)
z

In [56]:
for i in z:
    print(i)

-11
3
1
8
0


### Read and process csv files

In [57]:
!ls

 Class1    Class3   Class7   HandsOn   omp
 Class11   Class5   Class9   mpg.csv  'Refreshing python.ipynb'


In [58]:
!head mpg.csv

"","manufacturer","model","displ","year","cyl","trans","drv","cty","hwy","fl","class"
"1","audi","a4",1.8,1999,4,"auto(l5)","f",18,29,"p","compact"
"2","audi","a4",1.8,1999,4,"manual(m5)","f",21,29,"p","compact"
"3","audi","a4",2,2008,4,"manual(m6)","f",20,31,"p","compact"
"4","audi","a4",2,2008,4,"auto(av)","f",21,30,"p","compact"
"5","audi","a4",2.8,1999,6,"auto(l5)","f",16,26,"p","compact"
"6","audi","a4",2.8,1999,6,"manual(m5)","f",18,26,"p","compact"
"7","audi","a4",3.1,2008,6,"auto(av)","f",18,27,"p","compact"
"8","audi","a4 quattro",1.8,1999,4,"manual(m5)","4",18,26,"p","compact"
"9","audi","a4 quattro",1.8,1999,4,"auto(l5)","4",16,25,"p","compact"


In [59]:
import csv
%precision 2
with open('mpg.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))

Now mpg is a list of dictionaries (one dictionary per row of the csv file)

In [60]:
len(mpg)

234

In [61]:
mpg[0]

OrderedDict([('', '1'),
             ('manufacturer', 'audi'),
             ('model', 'a4'),
             ('displ', '1.8'),
             ('year', '1999'),
             ('cyl', '4'),
             ('trans', 'auto(l5)'),
             ('drv', 'f'),
             ('cty', '18'),
             ('hwy', '29'),
             ('fl', 'p'),
             ('class', 'compact')])

In [62]:
mpg[1]

OrderedDict([('', '2'),
             ('manufacturer', 'audi'),
             ('model', 'a4'),
             ('displ', '1.8'),
             ('year', '1999'),
             ('cyl', '4'),
             ('trans', 'manual(m5)'),
             ('drv', 'f'),
             ('cty', '21'),
             ('hwy', '29'),
             ('fl', 'p'),
             ('class', 'compact')])

In [63]:
mpg[1]['manufacturer']

'audi'

In [64]:
mpg[1].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

Print the average miles-per-gallon in the city (cty column):

In [65]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

In [66]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

23.44

We can use set() to get the unique values for the number of cylinders

In [67]:
cylinders=set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

Question: what is the city fuel economy (cty) of the cars depending on the number of cylinders?

In [68]:
CtyByCyl=[]
for c in cylinders:
    summpg=0
    cyltypecount=0
    for d in mpg:
        if(d['cyl']==c):
            summpg+=float(d['cty'])
            cyltypecount+=1
    CtyByCyl.append((c,summpg/cyltypecount))
CtyByCyl.sort(key=lambda x: x[0])
CtyByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

Exercise: what is the city fuel economy (cty) of the cars depending on the class of the car

In [69]:
%%time
vclasses=set(d['class'] for d in mpg)
CtyByClass=[]
for c in vclasses:
    summpg=0
    classtypecount=0
    for d in mpg:
        if(d['class']==c):
            summpg+=float(d['cty'])
            classtypecount+=1
    CtyByClass.append((c,summpg/classtypecount))
CtyByClass.sort(key=lambda x: x[1])
CtyByClass

CPU times: user 210 µs, sys: 47 µs, total: 257 µs
Wall time: 259 µs


Excercise. More efficient implementation?

In [114]:
%%time
# Your implementation here:

CPU times: user 253 µs, sys: 10 µs, total: 263 µs
Wall time: 279 µs


In [70]:
def lento(mpg):
    vclasses=set(d['class'] for d in mpg)
    CtyByClass=[]
    for c in vclasses:
        summpg=0
        classtypecount=0
        for d in mpg:
            if(d['class']==c):
                summpg+=float(d['cty'])
                classtypecount+=1
        CtyByClass.append((c,summpg/classtypecount))
    CtyByClass.sort(key=lambda x: x[1])
    CtyByClass
    
%timeit lento(mpg)

134 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [119]:
def rapido(mpg):
# copy your optimized implementation here

%timeit rapido(mpg)

148 µs ± 539 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### The Numpy library
More efficient alternative to work with arrays

In [71]:
import numpy as np

#### Creating Arrays

Create a list and convert it to a numpy array

In [72]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [73]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [74]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [75]:
m.shape

(2, 3)

<br>
`arange` returns evenly spaced values within a given interval.

In [76]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [77]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [78]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

<br>
`resize` changes the shape and size of array in-place.

In [79]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [80]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [81]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [82]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [83]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

<br>
Create an array using repeating list (or see `np.tile`)

In [84]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [85]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
#### Combining Arrays

In [86]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [87]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [88]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

#### Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [89]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [90]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [91]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [92]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [93]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [94]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>
The shape of array `z` is `(2,3)` before transposing.

In [95]:
z.shape

(2, 3)

<br>
Use `.T` to get the transpose.

In [96]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [97]:
z.T.shape

(3, 2)

<br>
Use `.dtype` to see the data type of the elements in the array.

In [98]:
z.dtype

dtype('int64')

<br>
Use `.astype` to cast to a specific type.

In [99]:
z = z.astype('f')
z.dtype

dtype('float32')

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [100]:
a = np.array([-4, -2, 1, 3, 5])

In [101]:
a.sum()

3

In [102]:
a.max()

5

In [103]:
a.min()

-4

In [104]:
a.mean()

0.6

In [105]:
a.std()

3.2619012860600183

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [106]:
a.argmax()

4

In [107]:
a.argmin()

0

<br>
## Indexing / Slicing

In [108]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [109]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [110]:
s[1:5]

array([ 1,  4,  9, 16])

<br>
Use negatives to count from the back.

In [111]:
s[-4:]

array([ 81, 100, 121, 144])

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [112]:
s[-5::-2]

array([64, 36, 16,  4,  0])

<br>
Let's look at a multidimensional array.

In [113]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Use bracket notation to slice: `array[row, column]`

In [114]:
r[2, 2]

14

<br>
And use : to select a range of rows or columns

In [115]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [116]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [117]:
r[-1, ::2]

array([30, 32, 34])

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [118]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [119]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [120]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [121]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` has also been changed!

In [122]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [123]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [124]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [125]:
test = np.random.randint(0, 10, (4,3))
test

array([[8, 7, 2],
       [1, 3, 2],
       [5, 6, 5],
       [1, 4, 6]])

<br>
Iterate by row:

In [126]:
for row in test:
    print(row)

[8 7 2]
[1 3 2]
[5 6 5]
[1 4 6]


<br>
Iterate by index:

In [127]:
for i in range(len(test)):
    print(test[i])

[8 7 2]
[1 3 2]
[5 6 5]
[1 4 6]


<br>
Iterate by row and index:

In [128]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [8 7 2]
row 1 is [1 3 2]
row 2 is [5 6 5]
row 3 is [1 4 6]


<br>
Use `zip` to iterate over multiple iterables.

In [129]:
test2 = test**2
test2

array([[64, 49,  4],
       [ 1,  9,  4],
       [25, 36, 25],
       [ 1, 16, 36]])

In [130]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[8 7 2] + [64 49  4] = [72 56  6]
[1 3 2] + [1 9 4] = [ 2 12  6]
[5 6 5] + [25 36 25] = [30 42 30]
[1 4 6] + [ 1 16 36] = [ 2 20 42]


# Content not covered today
* Working with time data (datatime and time modules)
* Object oriented programing (classes and objects)

We'll cover these if time permits